version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 2  
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Run Hello test
          command: |
            touch src/test_hello.sh
            circleci tests glob "**/*.sh" | circleci tests split --split-by=timings
            bash src/test_hello.sh
      - run:
          name: Run Goodbye test
          command: |
            touch src/test_goodbye.sh
            bash src/test_goodbye.sh
workflows:
  version: 2
  test:
    jobs:
      - test
