version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 2  
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Run Hello test
          command: |
            circleci tests glob "src/test_*.sh" | circleci tests split --split-by=timings > /tmp/test_run
            bundle exec bash $(cat /tmp/test_run)
            
workflows:
  version: 2
  test:
    jobs:
      - test
